#!/bin/bash
# Note: postrm (script executed after uninstalling the package)
# set -e


if [ -f /bin/solarfm ]; then
    rm /bin/solarfm
fi

if [ -f /opt/solarfm.zip ]; then
    rm /opt/solarfm.zip
fi
